### PR TITLE
Changes to zip method and zip testing

### PR DESCRIPTION
**Pull request by dpgraham**
* Refactored the `zip.toInMemoryZip` to not use temporary directory as writeStream but instead uses an ad-hoc writeStream that writes the zip buffers to an array and then concatenates them together at the end (In an earlier PR Isaac pointed out that file write streams were being used unnecessarily and it occurred to me that the file stream was unnecessary in this method)
* Refactored `zip-specs.js` to use mock filesystem instead of the actual filesystem
* Updated the documentation to include the zip methods

### CODE REVIEW

**Comment by imurchie** [comment]
@dpgraham Is this still on the go?

**Comment by dpgraham** [comment]
I still need to commit this. Let me fix the conflicts and then I'll merge it.

**Comment by imurchie** [comment]
👍

**Comment by dpgraham** [comment]
Published to appium-support@2.8.2

**Pull request merged**
