### PR TITLE
Fix uploading of files

### PR DESCRIPTION
**Pull request by imurchie**
Fix importing and using of `fs` module.

Fixes https://github.com/appium/appium/issues/10630

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
Thanks

**Comment by hursevich** [comment]
Thanks, guys for quick fix! Waiting for next release to check, not sure how the ticket resolution flow is working in Appium development?

**Comment by jlipps** [comment]
@hursevich this has not yet been merged. when it is, the package will then need to be published, at which point the update is usually available by reinstalling the beta version of appium via npm.

**Comment by imurchie** [comment]
It fixes it in that `exists` is called in the context of `fs`, rather than nothing. `fs.exists` is just a helper, calling `this.hasAccess` (https://github.com/appium/appium-support/blob/master/lib/fs.js#L23), which is not there when the function is called alone, without binding first.

**Comment by imurchie** [comment]
Published in `appium-support@2.16.1`.

**Comment by jlipps** [comment]
ahh, it was a binding issue. ok 👍

**Pull request merged**
