### PR TITLE
Added hasContent/Value

### PR DESCRIPTION
**Pull request by 0x1mason**
@sebv @jlipps Please take a look at this.  This is for the xcode version changes.  I moved the the `notNullOrUndefined` functions here and renamed them to `hasContent` and `hasValue`.

### CODE REVIEW

**Comment by sebv** [comment]
`hasValue` I understand, `hasContent` I am not sure is really needed, maybe a string specific method would be better (using 1typeof1). Also could add support `bool`, cause this is the most annoying case.

**Comment by 0x1mason** [comment]
@sebv `bool` is supported.  Checkout the unit tests. `hasValue(false)` should be `true`.

A good example for `hasContent` is `hasContent(path) ? doSomething(path) : throw "Invalid path";

**Comment by 0x1mason** [comment]
Nm, I think I see your pt regaring `hasContent`, you mean keep it but take out `isNumber`.  Sure that works.

**Comment by 0x1mason** [comment]
@sebv Ok checkout `hasContent` now.

**Comment by 0x1mason** [comment]
@jlipps has seen these functions before and sebv gave his assent to the hasContent changes, so merging.  Lmk if there are concerns and I will revert.

**Pull request merged**
