### PR TITLE
Issue  #13515

### PR DESCRIPTION
**Pull request by anorimaki**
Pull request to fix https://github.com/appium/appium/issues/13515

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
Thanks for the fix @anorimaki 
Could you please sign the CLA?

**Comment by anorimaki** [comment]
> 
> 
> Thanks for the fix @anorimaki
> Could you please sign the CLA?

I have signed it but the check still is pending. I don't know what else I have to do.

**Comment by mykola-mokhnach** [comment]
You should make sure the email address you used to sign the CLA is the same as the email address in the local config of git from which the PR has been prepared.
As an option you could fix the local email address and then rebase the PR

**Comment by anorimaki** [comment]
> 
> 
> @anorimaki Seems like the bot still cannot figure it out :( . Would you mind opening a new PR with fixed email address? It must work then

https://github.com/appium/appium-support/pull/139
Let's see if there is more luck now :)

**Pull request closed without merging**
