### PR TITLE
Nodeify module

### PR DESCRIPTION
**Pull request by Jonahss**
This code just copied from future.js in appium, so that we don't have to copy code between different future.js files in different appium modules

### CODE REVIEW

**Comment by jlipps** [comment]
please squash to one commit

**Comment by Jonahss** [comment]
@jlipps does that mean that after squashing it can be merged?

For clarity's sake I'd like to submit PRs as multiple commits, then squash before merging. Is that an acceptable approach going forward?

**Comment by jlipps** [comment]
yep, LGTM after squashing. your approach sounds fine. i'll try to remember to give all other kinds of feedback before asking to squash

**Comment by Jonahss** [comment]
lol. LGTS

**Pull request merged**
